modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Renzolc/enhanced-mob-spawners-neoforge/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Renzolc/enhanced-mob-spawners-neoforge"
iconFile="assets/spawnermod/icon.png"
authors="${mod_authors}"
description='''${mod_description}

NeoForge port of Enhanced Mob Spawners (Fabric). Original author: Branders / Anders Blomqvist.
'''

[[mixins]]
config="spawnermod.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="optional"
    versionRange="[5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="supplementaries"
    type="optional"
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"
